project_id = "vhaizqhkodqyqplpqcss"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://beta.lightshunt.com"
additional_redirect_urls = ["https://localhost:3000", "https://beta.lightshunt.com", "https://beta.lightshunt.com/auth/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[realtime]
enabled = true

[functions]
[functions.seed-display-history]
verify_jwt = true
