// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhaizqhkodqyqplpqcss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoYWl6cWhrb2RxeXFwbHBxY3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTU1NDAsImV4cCI6MjA1NzU5MTU0MH0.nbYlbIB6ckCdL3c96Z0gB-dmNHZuonPLAoGVTMStlWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);