// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Ensure environment variables are available
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const error = new Error('Missing Supabase environment variables. Please check your .env file.');
  console.error(error);
  // Only throw in development to avoid exposing sensitive info in production
  if (import.meta.env.DEV) {
    throw error;
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);